name: clearclimate-ws4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - xarray
  - netcdf4
  - dask
  - numpy
  - pandas
  - matplotlib
  - cartopy
  - tqdm
  - jupyterlab
  - pip
  - xesmf
  - pip:
      - einops
      - xbatcher
