name: clearclimate-ws4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - xarray
  - netcdf4
  - dask
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - jupyterlab
  - pip
  - pip:
      - einops
